apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux.yaml


generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
- name: gopass-init
  namespace: flux
  files:
    - initialize_gopass.sh

